### PR TITLE
AcroPlus for Brain

### PR DESCRIPTION
**Pull request by fujin**
Per https://github.com/TauLabs/TauLabs/issues/1778, AcroPlus (gyro suppression)
- Featuring OSD Menu configuration capabilities booyakasha.

We should probably wait till this is merged upstream but wanted to send/open this for the future.

### CODE REVIEW

**Comment by fujin** [comment]
Flight tested today. Checked OSD Menu at the field; tweaked insanity factor.

**Comment by fujin** [comment]
I made it such that the osd displays `ACRO PLUS` when in A+. :metal: When/if this lands upstream, I'll drop the common commit out

**Comment by BrainFPV** [comment]
@fujin thanks, looks good. If you don't mind, can you also add the mode to the `flightmode_menu`?

**Comment by fujin** [comment]
@BrainFPV definitely, will do! I will rebase this now and drop out the Stabilization commit as well.

**Comment by fujin** [comment]
I rebased out the innerloop stabilization upstream commit so this is good to go whenever you next catch up to next.

**Pull request merged**
