### PR TITLE
ChibiOS/RT for BrainFPV

### PR DESCRIPTION
**Pull request by fujin**
- I studied the Quanton changeset @
  https://github.com/TauLabs/TauLabs/commit/eab08607eb476053003c04009faafd90523bd136
- Builds locally, flashed to board fine, booted OK. Do not have SWD
  debugging capabilities to do what is hinted at in [pios_config.h re: calibration.](https://github.com/fujin/TauLabs/commit/fced0027dbdbd3e2e940973155de609fb4da89ca#diff-ce4254f1acfbf104f6a032537e8c177fR125) @peabody124 said to use the Quanton value, so I went with that for now. I updated the comment copied from Quanton.

### CODE REVIEW

**Comment by fujin** [comment]
I have no familiarity with this code, so please forgive any mistakes, I'm sure there is probably some hal/mcu configuration and potentially IRQ routing or something like that; I don't know if you had any other outstanding chibios/rt work.

**Comment by fujin** [comment]
PFD

**Comment by fujin** [comment]
I merged the new hpwm stuff into another branch (can't really test fly without it.. all my escs are oneshot).. https://github.com/fujin/TauLabs/tree/brain-chibios-hpwm, flashed to board, OSD is working, motors report they have received neutral idle tone.. CPU usage is sitting at 30% on OSD.. had to move the climb rate over a little bit (partially blocked by G-force).. waiting for more testing this afternoon heads up @BrainFPV

**Comment by fujin** [comment]
I guess I could be testing on the older oneshot channeltype

**Comment by BrainFPV** [comment]
@fujin great work! I think we should hold off with moving Brain to ChibiOS until after the next release. I will test this and then we can have `brain_chibios` branch that will merge into `brain` once we have tested it thoroughly.

**Comment by BrainFPV** [comment]
@fujin thanks! I did some initial tests and everything looks good :). I merged it into the `brain_chibios` branch, which we can use for further testing. I will keep this branch in sync with `brain`; if you issue a PR, only target `brain_chibios` if it is ChibiOS related.

PS: You should disable the white space hook

**Pull request closed without merging**
